Add MessageBroker and MessageQueue
BroEnotiKa/zhalobobot pull request #3
Opened 2022-03-13 15:26 UTC by BroEnotiKa

2022-03-16 11:26 UTC, disturm requested changes

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/Core/MessageQueue.cs
> +    private readonly ConcurrentDictionary<MessagePriority, ConcurrentQueue<Task<Message>>> priorityToQueue;
Похоже тут можно использовать просто Dictionary вместо ConcurrentDictionary, т.к. множество приоритетов постоянно.

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            }
Возможно так было бы более лаконично, т.к. нет повторения кода обновления (при этом код может быть некорректен, я его в блокноте написал)

```
foreach (var (groupId, oldResult) in groupIdToQueue)
{
    var foundValue = true;
    while (true)
    {
        if (!foundValue || oldResult.SendCountPerMinute == 0)
            break;
        if (groupIdToQueue.TryUpdate(groupId, (oldResult.Queue, 0), oldResult))
            break;
        foundValue = groupIdToQueue.TryGetValue(groupId, out oldResult);
    }    
}
```

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            groupIdToQueue[groupId] = (new MessageQueue(), 0);
Кажется нет гарантий, что сюда не может вклиниться другой поток и тогда будет создано две очереди сообщений для groupId. Хотя похоже сообщение все же не потеряется, т.к. дальше ты используешь не локальную очередь, а фактически добавленную

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +                await taskToExecute;
Здесь мы только ожидаем выполнения задания. Значит само задание было запущено ранее. И, если это задание заключается в отправке сообщения, то сообщение уже отправлено до добавления в очередь... А значит лимиты никак не работают: задания ожидаются по лимитам, а запускаются без лимитов.

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +                if (!userMessageQueue.TryDequeue(priority, out var taskToExecute) || taskToExecute == null)
Задание должно запускаться только в момент доставания его из очереди

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +        var allowedCount = MessageBrokerSettings.UserMessagesLimit;
Верно ли, что UserMessagesLimit - это лимит в секунду? Если да, то это стоит отразить в названии. Если нет, то с ним вообще иначе работать надо.

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +        executeUserMessagesRoutine = new AsyncPeriodicalAction(ExecuteUserMessages, LogError, () => TimeSpan.FromSeconds(1));
Верно ли, что 1 секунда будет отсчитываться не с начала прошлого запуска задачи, а после его окончания?
Если с начала, то при тупеже в ExecuteUserMessages возможно наслоение.

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            if (sendPerMinuteCount >= MessageBrokerSettings.GroupMessagesPerMinuteLimit)
Странно, что настройки передаются через глобальную переменную, а не через конструктор

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            }
Повторяется код из UserTasksToExecute с точностью до того, что в одном случае счетчик увеличивается, а в другом уменьшается. DRY

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/Settings/MessageBrokerSettings.cs
> +    internal static int GroupMessagesPerMinuteLimit { get; set; } = 16; // note (d.stukov): max allowed ~20
Кажется из-за того, что минута в Telegram и минута в очереди могут наслаиваться друг на друга по-разному, то лимит в нашей очереди должен быть в 2 раза меньше, чем лимит в Telegram.

Пример: в конце первой минуты отправили 16 сообщений, в начале второй минуты отправили 16 сообщений. С нашей точки зрения все ок, а лимит в Telegram превышен.

2022-03-16 11:26 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +    internal IEnumerable<Task<Message>> UserTasksToExecute()
наверное все же private

2022-03-19 09:02 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/Core/MessageQueue.cs
> +    private readonly ConcurrentDictionary<MessagePriority, ConcurrentQueue<Task<Message>>> priorityToQueue;
Да, согласен

2022-03-19 09:02 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            groupIdToQueue[groupId] = (new MessageQueue(), 0);
Невнимательность, исправил

2022-03-19 09:03 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +                await taskToExecute;
Угу, глупый баг получился, переделал через Func'и

2022-03-19 09:04 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +                if (!userMessageQueue.TryDequeue(priority, out var taskToExecute) || taskToExecute == null)
+

2022-03-19 09:11 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +        executeUserMessagesRoutine = new AsyncPeriodicalAction(ExecuteUserMessages, LogError, () => TimeSpan.FromSeconds(1));
После окончания

2022-03-19 09:12 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            }
+

2022-03-19 09:14 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/Settings/MessageBrokerSettings.cs
> +    internal static int GroupMessagesPerMinuteLimit { get; set; } = 16; // note (d.stukov): max allowed ~20
Это да, но в 2 раза резать тоже как-то не очень хочется, тут спасёт механизм, когда мы невыполненные таски будем обратно в очередь класть

2022-03-19 09:14 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +    internal IEnumerable<Task<Message>> UserTasksToExecute()
+

2022-03-19 09:19 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            if (sendPerMinuteCount >= MessageBrokerSettings.GroupMessagesPerMinuteLimit)
\+

2022-03-19 09:31 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +        executeUserMessagesRoutine = new AsyncPeriodicalAction(ExecuteUserMessages, LogError, () => TimeSpan.FromSeconds(1));
Точнее, даже не так, там чуть более хитрая реализация:<br/>
Допустим, запускаем action на N секунд, если прошло меньше N - дожидаемся, пока не пройдет N. Если больше - дожидаемся завершения action'a, после чего немедленно запускаем следующую итерацию

2022-03-19 09:32 UTC, BroEnotiKa commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            }
\+

2022-03-19 09:42 UTC, merged

2022-03-21 14:01 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +        => await Task.WhenAll(GroupItemsToExecute(MessageBrokerSettings.GroupMessagesPerMinuteLimit).Select(Execute));
"Странно, что настройки передаются через глобальную переменную, а не через конструктор"

Вот и верь тебе, когда ты ставишь "+"

2022-03-21 14:01 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +            if (e.ErrorCode != 429)
Кажется тебе надо поменять if и else. Логически все корректно, но странно видеть код обработки специфичной ошибки 429 в блоке else...

2022-03-21 14:01 UTC, disturm commented on Zhalobobot.TelegramMessageQueue/MessageBroker.cs
> +                    groupIdToQueue[item.GroupChatId.Value].Queue.Enqueue(item);
Идея с повторным добавлением в очередь выглядит интересно. Но кажется сейчас, если вдруг этот код отработает, например, на последнем сообщении в очереди, то это сообщение будет посылаться подряд без задержек до исчерпания локального лимита. Кажется, все же, при ошибки лимита надо делать паузу в разборе очереди.